"""add tags to posts

Revision ID: 384b59db24a5
Revises: 1f9d454d12d1
Create Date: 2026-06-30 19:00:26.682263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384b59db24a5'
down_revision = '1f9d454d12d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
