"""add password_hash and password_salt

Revision ID: 79c8ef4d2ad6
Revises: 384b59db24a5
Create Date: 2026-07-01 01:56:02.715806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c8ef4d2ad6'
down_revision = '384b59db24a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_salt', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_salt')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
